<?php

/**
 * Implements hook_views_api().
 */
function blog_archive_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'blog_archive'),
  );
}

/**
 * Implements hook_views_default_views().
 */
function blog_archive_views_default_views() {
  return blog_archive_block();
}

/**
 * Begin view
 */
function blog_archive_block() {
$view = new view();
$view->name = 'blogger_archive';
$view->description = 'A block view that replicates the blogger archive of dates and posts.';
$view->tag = 'default';
$view->base_table = 'node';
$view->human_name = 'Blogger Archive';
$view->core = 7;
$view->api_version = '3.0';
$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

/* Display: Master */
$handler = $view->new_display('default', 'Master', 'default');
$handler->display->display_options['title'] = 'Архив блога';
$handler->display->display_options['css_class'] = 'archive-block';
$handler->display->display_options['use_more_always'] = FALSE;
$handler->display->display_options['use_more_text'] = 'ещё';
$handler->display->display_options['access']['type'] = 'none';
$handler->display->display_options['cache']['type'] = 'none';
$handler->display->display_options['query']['type'] = 'views_query';
$handler->display->display_options['exposed_form']['type'] = 'basic';
$handler->display->display_options['exposed_form']['options']['submit_button'] = 'Применить';
$handler->display->display_options['exposed_form']['options']['reset_button_label'] = 'Сбросить';
$handler->display->display_options['exposed_form']['options']['exposed_sorts_label'] = 'Сортировать по';
$handler->display->display_options['exposed_form']['options']['sort_asc_label'] = 'По возрастанию';
$handler->display->display_options['exposed_form']['options']['sort_desc_label'] = 'По убыванию';
$handler->display->display_options['pager']['type'] = 'none';
$handler->display->display_options['style_plugin'] = 'list';
$handler->display->display_options['style_options']['grouping'] = array(
  0 => array(
    'field' => 'created',
    'rendered' => 1,
    'rendered_strip' => 0,
  ),
);
$handler->display->display_options['style_options']['default_row_class'] = FALSE;
$handler->display->display_options['row_plugin'] = 'fields';
/* Поле: Содержимое: Дата публикации */
$handler->display->display_options['fields']['created']['id'] = 'created';
$handler->display->display_options['fields']['created']['table'] = 'node';
$handler->display->display_options['fields']['created']['field'] = 'created';
$handler->display->display_options['fields']['created']['label'] = '';
$handler->display->display_options['fields']['created']['exclude'] = TRUE;
$handler->display->display_options['fields']['created']['alter']['alter_text'] = TRUE;
$handler->display->display_options['fields']['created']['alter']['text'] = ' <span class="collapse-icon">►</span> [created]';
$handler->display->display_options['fields']['created']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['created']['date_format'] = 'custom';
$handler->display->display_options['fields']['created']['custom_date_format'] = 'M Y';
$handler->display->display_options['fields']['created']['second_date_format'] = 'long';
/* Поле: Содержимое: Заголовок */
$handler->display->display_options['fields']['title']['id'] = 'title';
$handler->display->display_options['fields']['title']['table'] = 'node';
$handler->display->display_options['fields']['title']['field'] = 'title';
$handler->display->display_options['fields']['title']['label'] = '';
$handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
$handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
/* Критерий сортировки: Содержимое: Дата публикации */
$handler->display->display_options['sorts']['created']['id'] = 'created';
$handler->display->display_options['sorts']['created']['table'] = 'node';
$handler->display->display_options['sorts']['created']['field'] = 'created';
$handler->display->display_options['sorts']['created']['order'] = 'DESC';
/* Контекстный фильтр: Содержимое: Дата создания */
$handler->display->display_options['arguments']['created_fulldate']['id'] = 'created_fulldate';
$handler->display->display_options['arguments']['created_fulldate']['table'] = 'node';
$handler->display->display_options['arguments']['created_fulldate']['field'] = 'created_fulldate';
$handler->display->display_options['arguments']['created_fulldate']['exception']['title'] = 'Все';
$handler->display->display_options['arguments']['created_fulldate']['default_argument_type'] = 'fixed';
$handler->display->display_options['arguments']['created_fulldate']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['created_fulldate']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['created_fulldate']['summary_options']['items_per_page'] = '25';
/* Критерий фильтра: Содержимое: Опубликовано */
$handler->display->display_options['filters']['status']['id'] = 'status';
$handler->display->display_options['filters']['status']['table'] = 'node';
$handler->display->display_options['filters']['status']['field'] = 'status';
$handler->display->display_options['filters']['status']['value'] = 1;
$handler->display->display_options['filters']['status']['group'] = 1;
$handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;

/* Display: Blogger Archive Block */
$handler = $view->new_display('block', 'Blogger Archive Block', 'block');
$handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
$translatables['blogger_archive'] = array(
  t('Master'),
  t('Архив блога'),
  t('ещё'),
  t('Применить'),
  t('Сбросить'),
  t('Сортировать по'),
  t('По возрастанию'),
  t('По убыванию'),
  t(' <span class="collapse-icon">►</span> [created]'),
  t('Все'),
  t('Blogger Archive Block'),
);
  $views[$view->name] = $view;
  return $views;
}
